name = "edge"
compatibility_date = "2024-01-01"

main = "src/global.mjs"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "edge_ChatRoom" },
  { name = "limiters", class_name = "edge_RateLimiter" },
]
[[d1_databases]]
binding = "EDGE_DB"  # ← harus sama dengan "EDGE_DB"
database_name = "app-readtalk"
database_id = "25896737-e0e8-4561-8cc6-f5841430d1c8"

[[kv_namespaces]]
binding = "EDGE_KV"  # ← harus sama dengan "EDGE_KV"
id = "72b81feecbfc4a56b06d55f812e04e9d"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1


[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false


[[migrations]]
tag = "v1"                                       
new_sqlite_classes = ["edge_ChatRoom", "edge_RateLimiter"]
